version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: youruser
      MONGO_INITDB_ROOT_PASSWORD: yourpassword

volumes:
  mongodbdata: